using System.Linq.Expressions;
namespace MaxicanResturant.Models
{
    public interface IRepository<T> where T : class
    {
        Task<IEnumerable<T>> GetAllAsync(); // This method is an asynchronous operation that retrieves all entities of type T from the database. It returns a Task that represents the asynchronous operation and contains an IEnumerable<T> as the result, which is a collection of all the entities of type T retrieved from the database. By calling this method, you can get a list of all records of the specified type from the database in an asynchronous manner, allowing for efficient data retrieval without blocking the main thread of execution.

        Task<IEnumerable<T>> GetAllByIdAsync<TKey>(TKey id, string propertyName, QueryOptions<T> options); // This method is an asynchronous operation that retrieves a collection of entities of type T from the database based on a specified identifier. It takes three parameters: id, which is the identifier value to filter the entities; propertyName, which is the name of the property in the entity that corresponds to the identifier; and options, which is an instance of QueryOptions<T> that allows you to specify additional query options such as filtering, sorting, and including related entities. The method returns a Task that represents the asynchronous operation and contains an IEnumerable<T> as the result, which is a collection of entities of type T that match the specified identifier and query options. By calling this method, you can retrieve a filtered list of records based on a specific identifier while also applying additional query options for more flexible data retrieval.

        Task<T> GetByIdAsync(int id, QueryOptions<T> options); // This method is an asynchronous operation that retrieves a single entity of type T from the database based on a specified identifier. It takes two parameters: id, which is the identifier value to filter the entity; and options, which is an instance of QueryOptions<T> that allows you to specify additional query options such as filtering, sorting, and including related entities. The method returns a Task that represents the asynchronous operation and contains an instance of type T as the result, which is the entity that matches the specified identifier and query options. By calling this method, you can retrieve a specific record based on its unique identifier while also applying additional query options for more flexible data retrieval.
        Task AddAsync(T entity); // This method is an asynchronous operation that adds a new entity of type T to the database. It takes a single parameter, entity, which is the instance of type T that you want to add to the database. The method returns a Task that represents the asynchronous operation, allowing you to perform the add operation without blocking the main thread of execution. By calling this method, you can insert a new record into the database for the specified entity type in an asynchronous manner, ensuring efficient data manipulation while maintaining responsiveness in your application.
        Task UpdateAsync(T entity); // This method is an asynchronous operation that updates an existing entity of type T in the database. It takes a single parameter, entity, which is the instance of type T that you want to update in the database. The method returns a Task that represents the asynchronous operation, allowing you to perform the update operation without blocking the main thread of execution. By calling this method, you can modify an existing record in the database for the specified entity type in an asynchronous manner, ensuring efficient data manipulation while maintaining responsiveness in your application.
        Task DeleteAsync(int id); // This method is an asynchronous operation that deletes an entity of type T from the database based on a specified identifier. It takes a single parameter, id, which is the identifier value of the entity you want to delete. The method returns a Task that represents the asynchronous operation, allowing you to perform the delete operation without blocking the main thread of execution. By calling this method, you can remove a specific record from the database for the specified entity type based on its unique identifier in an asynchronous manner, ensuring efficient data manipulation while maintaining responsiveness in your application.
    }
}
